name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_LEANCLOUD_APP_ID: ${{ secrets.VITE_LEANCLOUD_APP_ID }}
          VITE_LEANCLOUD_APP_KEY: ${{ secrets.VITE_LEANCLOUD_APP_KEY }}
          VITE_LEANCLOUD_SERVER_URL: ${{ secrets.VITE_LEANCLOUD_SERVER_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
